### ISSUE TITLE
Delete Media

### ISSUE THREAD

**Issue by imyxuan** [tomatophp/filament-media-manager#20]
how can i  just delete one media not the whole folder?

**Comment by 3x1io** [comment]
![Screenshot 2024-09-29 at 12 14 26 PM](https://github.com/user-attachments/assets/c9a7c58c-daf4-43e7-a098-32eda82c9011)

just delete it from this button!

**Comment by imyxuan** [comment]
there is no delete button here, is something in my configuration?
![no buttons](https://github.com/user-attachments/assets/233b4675-f81a-45c6-88af-bfdc50d4ceb6)

**Comment by imyxuan** [comment]
problem fixed! Fixed by update the package version. Thank you!

**Comment by jfversat** [comment]
@imyxuan can you tell me what was the fix, Im using version 1.1.4 and tried 1.1.3 and still not getting the delete item button shown. also tried using dev-master and still did not work for me
